# docker-compose up -d

version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - mpjmp_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - mpjmp_network

  file-upload-service:
    build: ../backend/file-upload-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    env_file:
      - ../.env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mpjmp_network

  processing-service:
    build: ../backend/processing-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - mpjmp_network

  orchestrator-service:
    build: ../backend/orchestrator-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - mpjmp_network

  notification-service:
    build: ../backend/notification-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - mpjmp_network

  storage-service:
    build: ../backend/storage-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - mpjmp_network

networks:
  mpjmp_network:
    driver: bridge
