# docker-compose up -d

version: '3.8'
services:
  file-upload-service:
    build: ../backend/file-upload-service
    ports:
      - "8081:8081"
    networks:
      - mpjmp_network

  processing-service:
    build: ../backend/processing-service
    ports:
      - "8082:8082"
    networks:
      - mpjmp_network

  orchestrator-service:
    build: ../backend/orchestrator-service
    ports:
      - "8083:8083"
    networks:
      - mpjmp_network

  notification-service:
    build: ../backend/notification-service
    ports:
      - "8084:8084"
    networks:
      - mpjmp_network

  storage-service:
    build: ../backend/storage-service
    ports:
      - "8085:8085"
    networks:
      - mpjmp_network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

networks:
  mpjmp_network:
    driver: bridge
