apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-upload-service
  template:
    metadata:
      labels:
        app: file-upload-service
    spec:
      containers:
      - name: file-upload-service
        image: file-upload-service:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: file-upload-service
spec:
  selector:
    app: file-upload-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
