apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-service
  labels:
    app: orchestrator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: orchestrator-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8083"
    spec:
      containers:
      - name: orchestrator-service
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "kafka:9092"
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGODB_URI
          - name: JAVA_OPTS
            value: "-Xms256m -Xmx512m -XX:+UseG1GC"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        image: deployment-orchestrator-service:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8083
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  labels:
    app: orchestrator-service
spec:
  selector:
    app: orchestrator-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
