apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processing-service
  template:
    metadata:
      labels:
        app: processing-service
    spec:
      containers:
      - name: processing-service
        image: processing-service:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: processing-service
spec:
  selector:
    app: processing-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
