apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-service
  labels:
    app: processing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processing-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: processing-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
      - name: processing-service
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "kafka:9092"
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGODB_URI
          - name: JAVA_OPTS
            value: "-Xms256m -Xmx512m -XX:+UseG1GC"
          - name: PROCESSING_THREADS
            value: "4"
          - name: PROCESSING_BATCH_SIZE
            value: "100"
          - name: PROCESSING_DIR
            value: "/app/data/processing"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        image: deployment-processing-service:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8082
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: processing-service
  labels:
    app: processing-service
spec:
  selector:
    app: processing-service
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
