spring:
  application:
    name: orchestrator-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: earliest
